### ISSUE TITLE
Not compatible with Gatsby 5.7.0

### ISSUE THREAD

**Issue by bryanrtboy** [thomasgassmann/gatsby-plugin-sharp-exif#21]
I'm trying to extract EXIF image date and I get the error that it's not compatible with the current Gatsby version:

` Plugin gatsby-plugin-sharp-exif is not compatible with your gatsby version 5.7.0 - It requires gatsby@^2.0.0`

I can't seem to find a workaround or any other way to extract EXIF data from images. Is there any way to make this compatible or does Gatsby now have a way of getting to EXIF data in image files?

**Comment by thomasgassmann** [comment]
Sure. I haven't been maintaining the plugin very actively, but upgrading it to support newer Gatsby versions is definitely something I should consider. I will try updating it this weekend depending on how much time I have.

**Comment by thomasgassmann** [comment]
@bryanrtboy The plugin should have been updated to support Gatsby 5 now. Please try upgrading to `2.0.0`.

**Comment by bryanrtboy** [comment]
Thanks! I no longer get the error message but it did not fix the problem that I thought it was going to fix.  When I try to run your sample query in GraphiQL, it does not appear that a 'fields' node exists on the allImageSharp files. The plug-in runs because it identifies files where it 'can't read the exif data' on an image. I can see where your scripts adds a node named 'exif', but it doesn't show up for me and I can't see where you would have added a 'fields' node.

**Comment by thomasgassmann** [comment]
I believe `createNodeField` should do that for us. Can you maybe provide a set of files to reproduce the issue?

**Comment by bryanrtboy** [comment]
I have a git repo that you can use - https://github.com/bryanrtboy/gatsby-portfolio
It's based on a gatsby-image-gallery that I'm updating to accept folders of images. Does that work?

**Comment by bryanrtboy** [comment]
Cool! It finally recognized 'fields' and now I can query as long as the image file has data in that particular EXIF field:

`{
  allImageSharp {
    edges {
      node {
        fields {
          exif {
            raw {
              image {
                Artist
              }
            }
          }
        }
      }
    }
  }
}`
