### ISSUE TITLE
The plugin gatsby-plugin-sharp-exif@1.0.2 is using the API "transformExifToNodeData" which is not a known API

### ISSUE THREAD

**Issue by stotz89** [thomasgassmann/gatsby-plugin-sharp-exif#5]
Hi, just updated my gatsby project to gatsby@2.24.66 and also this plugin to version 1.0.2. When running gatsby develop or gatsby build following error occurs:
```
success open and validate gatsby-configs - 0.062s

 ERROR #11329 

Your plugins must export known APIs from their gatsby-node.js.

See https://www.gatsbyjs.org/docs/node-apis/ for the list of Gatsby node APIs.

- The plugin gatsby-plugin-sharp-exif@1.0.2 is using the API "transformExifToNodeData" which is not a known API.


```

Anyone else getting the same error?

**Comment by thomasgassmann** [comment]
This seems to have been caused by Gatbsy (since `gatsby@2.20.26`) now also validating exports from `gatsby-node`. It should be fixed in `gatsby-plugin-sharp-exif@1.0.3`.
